### ISSUE TITLE
Save Webhook Responses to Custom Table "TaskResult"

### ISSUE THREAD

**Issue by rajeshjoshi-dev** [webhookplan/webhookplan#1]
### Description

**Problem:**
Currently, WebhookPlan relies on `celery-task-results`, which presents limitations in terms of mapping and other constraints. As we aim to have greater control and flexibility, we need to implement a solution that allows us to save Webhook responses to a custom table named "TaskResult."

**Proposed Solution:**
Create a custom Django model named "TaskResult" to handle the storage of Webhook responses. This model should provide the necessary flexibility and mapping capabilities for our requirements.

### Requirements

- **Custom Model:**
  - Design and implement the "TaskResult" Django model to store Webhook responses.
  - Ensure that the model allows for comprehensive mapping and customization.

- **Database Integration:**
  - Update the database schema to accommodate the new "TaskResult" model.

- **WebhookPlan Logic:**
  - Integrate the new model into the WebhookPlan logic for seamless handling of Webhook responses.

### Additional Information

- **Context:**
  - We need this enhancement to have full control and flexibility over our Webhook responses.
  
- **Constraints:**
  - `celery-task-results` cannot be used due to limitations in mapping and other constraints.

### How to Contribute

1. Review the proposed solution and requirements.
2. If you have suggestions or improvements, please feel free to discuss them.

Let's work together to enhance WebhookPlan and make it even more powerful!

**Comment by amitsgh** [comment]
Hello @RajeshJ3, I stumbled upon this issue while searching for some 'good first issues' and I'd like to contribute to this.

**Comment by rajeshjoshi-dev** [comment]
@amitsgh, Thanks for showing interest in WebhookPlan.

Did you get what we exactly need?

Inside `api/schedules/models.py` you can create `TaskResult` model class. But, make sure to keep it future-proof and efficient enough. As we have retry functionality, so make sure to have `FK to self` (optionally). To link to previous results.

Fields as far I can think of are -

- `task` - FK to `django_celery_beat.models.PeriodicTask`
- `prev_result` - FK to `self`
- `metadata` - JSON field

- Fields to save whatever is returned from `api/tasks/webhook.py > api/tasks/webhook.py`

```python
return {
    "status": get_status_string(response_status),
    "http_status_code": response_status,
    "http_response_body": response_data,
    "request_ts": start_time,
    "dns_resolution_time": dns_duration,
    "ssl_handshake_time": ssl_duration,
    "request_time": request_duration,
    "total_time": total_time,
}
```

**Comment by amitsgh** [comment]
Got it! I'll proceed with the **TaskResult** model with the specified fields. Will reach out if any questions arise. Excited to contribute! 🚀

**Comment by amitsgh** [comment]
@RajeshJ3, while running the Docker container, I encountered the following error:

<img width="960" alt="image" src="https://github.com/webhookplan/webhookplan/assets/63700757/06a5a60c-dff2-4584-9be1-251b110ef8b8">

Also, the container is restarting automatically after a few seconds.

**Comment by rajeshjoshi-dev** [comment]
Did you ran the migrations?

To do so, ssh into the “django” container and run Django migrations.

or

Just remove the “command” from django container definition from the YAML.

**Comment by rajeshjoshi-dev** [comment]
> Just remove the “command” from django container definition from the YAML.

But, once migrations are made, add the command block back.

**Comment by amitsgh** [comment]
I haven't executed anything beyond building and running the container. Here, I'll proceed with the initial option of running the migration command in Django container. 

However, for future deployments, wouldn't it be beneficial to automatically apply migrations when the container starts?

**Comment by rajeshjoshi-dev** [comment]
For the production env. we have the migration command hardcoded in the Dockerfile. But, for development environment, we have to implement a better way to run migrations for the first time, when cloned the repo.

**Comment by amitsgh** [comment]
Hey @RajeshJ3, I made the custom model and hooked up the data, but I'm a bit stuck on the third part. Can you break it down for me? How does the new model fit into the WebhookPlan to handle responses smoothly?

**Comment by rajeshjoshi-dev** [comment]
So @amitsgh, what we want is, whenever a task is executed, its result should be saved into the db. In line `95` of `api/tasks/webhook.py` we need an entry of Task Result to be created.

**Please note:** To link `task` to this entry, use `pt_name` to find the existing task from the db.

**Comment by amitsgh** [comment]
Hey @RajeshJ3, I've run into an issue related to imports in the `webhook.py` file. It seems like there's an `AppRegistryNotReady` error when trying to import files in the `webhook.py` folder. The error stack trace indicates that the issue is arising from the `django_celery_beat.models` import in `schedules/models.py`. Specifically, it looks like the Django apps aren't loaded yet when trying to import this module.

```
File "/app/tasks/webhook.py", line 20, in <module>
from schedules.models import TaskResult
File "/app/schedules/models.py", line 2, in <module>
from django_celery_beat.models import PeriodicTask
```
```
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

I believe this issue is causing the Celery tasks to fail during initialization. Could you please take a look at this import and see if there's a circular dependency or if it needs to be adjusted to ensure proper app initialization?

Let me know if you need any additional information. Below is the full log of containers.

```
webhookplan_celery_beat    | Usage: celery [OPTIONS] COMMAND [ARGS]...
webhookplan_celery_beat    | Try 'celery --help' for help.
webhookplan_celery_beat    |
webhookplan_celery_beat    | Error: Invalid value for '-A' / '--app':
webhookplan_celery_beat    | Unable to load celery application.
webhookplan_celery_beat    | While trying to load the module core.celery the following error occurred:
webhookplan_celery_beat    | Traceback (most recent call last):
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/celery/bin/celery.py", line 58, in convert
webhookplan_celery_beat    |     return find_app(value)
webhookplan_celery_beat    |            ^^^^^^^^^^^^^^^
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/celery/app/utils.py", line 383, in find_app
webhookplan_celery_beat    |     sym = symbol_by_name(app, imp=imp)
webhookplan_celery_beat    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
webhookplan_celery_beat    |     module = imp(module_name, package=package, **kwargs)
webhookplan_celery_beat    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/celery/utils/imports.py", line 109, in import_from_cwd        
webhookplan_celery_beat    |     return imp(module, package=package)
webhookplan_celery_beat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
webhookplan_celery_beat    |     return _bootstrap._gcd_import(name[level:], package, level)
webhookplan_celery_beat    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_beat    |   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
webhookplan_celery_beat    |   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
webhookplan_celery_beat    |   File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
webhookplan_celery_beat    |   File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
webhookplan_celery_beat    |   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
webhookplan_celery_beat    |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
webhookplan_celery_beat    |   File "/app/core/__init__.py", line 2, in <module>
webhookplan_celery_beat    |     from tasks.webhook import webhook_job
webhookplan_celery_beat    |   File "/app/tasks/webhook.py", line 20, in <module>
webhookplan_celery_beat    |     from schedules.models import TaskResult
webhookplan_celery_beat    |   File "/app/schedules/models.py", line 2, in <module>
webhookplan_celery_beat    |     from django_celery_beat.models import PeriodicTask
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/django_celery_beat/models.py", line 78, in <module>
webhookplan_celery_beat    |     class SolarSchedule(models.Model):
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 129, in __new__
webhookplan_celery_beat    |     app_config = apps.get_containing_app_config(module)
webhookplan_celery_beat    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
webhookplan_celery_beat    |     self.check_apps_ready()
webhookplan_celery_beat    |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 138, in check_apps_ready       
webhookplan_celery_beat    |     raise AppRegistryNotReady("Apps aren't loaded yet.")
webhookplan_celery_beat    | django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
webhookplan_celery_beat    |
webhookplan_postgres       | 
webhookplan_postgres       | PostgreSQL Database directory appears to contain a database; Skipping initialization
webhookplan_postgres       |
webhookplan_celery_worker  | Usage: celery [OPTIONS] COMMAND [ARGS]...
webhookplan_celery_worker  | Try 'celery --help' for help.
webhookplan_celery_worker  |
webhookplan_celery_worker  | Error: Invalid value for '-A' / '--app':
webhookplan_celery_worker  | Unable to load celery application.
webhookplan_celery_worker  | While trying to load the module core.celery the following error occurred:
webhookplan_celery_worker  | Traceback (most recent call last):
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/celery/bin/celery.py", line 58, in convert
webhookplan_celery_worker  |     return find_app(value)
webhookplan_celery_worker  |            ^^^^^^^^^^^^^^^
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/celery/app/utils.py", line 383, in find_app
webhookplan_celery_worker  |     sym = symbol_by_name(app, imp=imp)
webhookplan_celery_worker  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
webhookplan_celery_worker  |     module = imp(module_name, package=package, **kwargs)
webhookplan_celery_worker  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/celery/utils/imports.py", line 109, in import_from_cwd        
webhookplan_celery_worker  |     return imp(module, package=package)
webhookplan_celery_worker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
webhookplan_celery_worker  |     return _bootstrap._gcd_import(name[level:], package, level)
webhookplan_celery_worker  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_worker  |   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
webhookplan_celery_worker  |   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
webhookplan_celery_worker  |   File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
webhookplan_celery_worker  |   File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
webhookplan_celery_worker  |   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
webhookplan_celery_worker  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
webhookplan_celery_worker  |   File "/app/core/__init__.py", line 2, in <module>
webhookplan_celery_worker  |     from tasks.webhook import webhook_job
webhookplan_celery_worker  |   File "/app/tasks/webhook.py", line 20, in <module>
webhookplan_celery_worker  |     from schedules.models import TaskResult
webhookplan_celery_worker  |   File "/app/schedules/models.py", line 2, in <module>
webhookplan_celery_worker  |     from django_celery_beat.models import PeriodicTask
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/django_celery_beat/models.py", line 78, in <module>
webhookplan_celery_worker  |     class SolarSchedule(models.Model):
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 129, in __new__
webhookplan_celery_worker  |     app_config = apps.get_containing_app_config(module)
webhookplan_celery_worker  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
webhookplan_celery_worker  |     self.check_apps_ready()
webhookplan_celery_worker  |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 138, in check_apps_ready       
webhookplan_celery_worker  |     raise AppRegistryNotReady("Apps aren't loaded yet.")
webhookplan_celery_worker  | django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
webhookplan_celery_worker  |
webhookplan_django         | Traceback (most recent call last):
webhookplan_django         |   File "/usr/local/bin/gunicorn", line 8, in <module>
webhookplan_django         |     sys.exit(run())
webhookplan_django         |              ^^^^^
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
webhookplan_django         |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/base.py", line 236, in run
webhookplan_django         |     super().run()
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/base.py", line 72, in run
webhookplan_django         |     Arbiter(self).run()
webhookplan_django         |     ^^^^^^^^^^^^^
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 58, in __init__
webhookplan_django         |     self.setup(app)
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/arbiter.py", line 118, in setup
webhookplan_django         |     self.app.wsgi()
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
webhookplan_django         |     self.callable = self.load()
webhookplan_django         |                     ^^^^^^^^^^^
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
webhookplan_django         |     return self.load_wsgiapp()
webhookplan_django         |            ^^^^^^^^^^^^^^^^^^^
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
webhookplan_django         |     return util.import_app(self.app_uri)
webhookplan_django         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/gunicorn/util.py", line 371, in import_app
webhookplan_django         |     mod = importlib.import_module(module)
webhookplan_django         |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_django         |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
webhookplan_django         |     return _bootstrap._gcd_import(name[level:], package, level)
webhookplan_django         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
webhookplan_django         |   File "<frozen importlib._bootstrap_external>", line 994, in exec_module
webhookplan_django         |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
webhookplan_django         |   File "/app/core/__init__.py", line 2, in <module>
webhookplan_django         |     from tasks.webhook import webhook_job
webhookplan_django         |   File "/app/tasks/webhook.py", line 20, in <module>
webhookplan_django         |     from schedules.models import TaskResult
webhookplan_django         |   File "/app/schedules/models.py", line 2, in <module>
webhookplan_django         |     from django_celery_beat.models import PeriodicTask
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/django_celery_beat/models.py", line 78, in <module>
webhookplan_django         |     class SolarSchedule(models.Model):
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 129, in __new__
webhookplan_django         |     app_config = apps.get_containing_app_config(module)
webhookplan_django         |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
webhookplan_django         |     self.check_apps_ready()
webhookplan_django         |   File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 138, in check_apps_ready       
webhookplan_django         |     raise AppRegistryNotReady("Apps aren't loaded yet.")
webhookplan_django         | django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by rajeshjoshi-dev** [comment]
@amitsgh This should be happening, can you share the whole file, where this is happening? Also, the `settings.py`.

**Comment by amitsgh** [comment]
@RajeshJ3, I apologize for the delay in addressing the GitHub issue. Unfortunately, I'm currently unable to dedicate time to it. I'm sorry for any inconvenience this may cause.
